#!/usr/bin/env bash
# Bootstrap the local-dev Garage S3 service started by e2e/docker-compose.yml.
# Idempotent: safe to re-run. Prints the env block at the end; paste it into
# e2e/.env once and from then on examples auto-load it.
#
# Run from the repo root:
#   docker compose -f e2e/docker-compose.yml up -d --wait
#   ./e2e/setup-garage.sh
#
# Override defaults via env:
#   CONTAINER=dlcdc-e2e-garage   (default; matches docker-compose.yml)
#   BUCKET=e2e                   (default)
#   KEY_NAME=e2e-app             (default)
#   ZONE=dc1                     (Garage layout zone; single-node, single-zone is fine)
#   CAPACITY=4G                  (advertised capacity for layout assign)

set -euo pipefail

CONTAINER="${CONTAINER:-dlcdc-e2e-garage}"
BUCKET="${BUCKET:-e2e}"
KEY_NAME="${KEY_NAME:-e2e-app}"
ZONE="${ZONE:-dc1}"
CAPACITY="${CAPACITY:-4G}"

E2E_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CREDS_FILE="${CREDS_FILE:-$E2E_DIR/.garage-bootstrap.env}"

# ---- helpers ---------------------------------------------------------------

garage() {
  docker exec "$CONTAINER" /garage "$@"
}

extract_field() {
  # extract_field "<text from `garage X info`>" "Field name"
  printf '%s\n' "$1" | awk -F': ' -v field="$2" '$1 == field { print $2 }'
}

wait_for_garage() {
  echo "==> waiting for $CONTAINER..."
  local attempts=0
  until garage status >/dev/null 2>&1; do
    sleep 1
    attempts=$((attempts + 1))
    if [[ $attempts -gt 60 ]]; then
      echo "garage did not come up within 60s; check 'docker logs $CONTAINER'" >&2
      exit 1
    fi
  done
}

bootstrap_layout() {
  echo "==> bootstrapping layout on $CONTAINER..."
  local full_id node_id next_version
  full_id="$(garage node id -q)"
  node_id="${full_id%%@*}"
  echo "    node id: $node_id"

  garage layout assign -z "$ZONE" -c "$CAPACITY" "$node_id" >/dev/null 2>&1 \
    || echo "    (layout already assigned for this node)"

  next_version="$(
    garage layout show 2>&1 \
      | grep -o 'apply --version [0-9][0-9]*' \
      | awk '{ print $3 }' \
      | tail -n 1
  )"
  next_version="${next_version:-1}"
  garage layout apply --version "$next_version" >/dev/null 2>&1 \
    || echo "    (layout already applied)"
}

ensure_bucket() {
  if garage bucket info "$BUCKET" >/dev/null 2>&1; then
    echo "==> bucket exists: $BUCKET"
    return
  fi
  echo "==> creating bucket: $BUCKET"
  garage bucket create "$BUCKET" >/dev/null
}

ensure_key() {
  # Sets ACCESS_KEY and SECRET_KEY env vars in the calling shell.
  local create_out existing_id
  if garage key info "$KEY_NAME" >/dev/null 2>&1; then
    existing_id="$(extract_field "$(garage key info "$KEY_NAME")" "Key ID")"
    if [[ -f "$CREDS_FILE" ]]; then
      # shellcheck disable=SC1090
      source "$CREDS_FILE"
      if [[ "${S3_ACCESS_KEY:-}" == "$existing_id" ]]; then
        echo "==> key exists and matches $CREDS_FILE: $KEY_NAME"
        return
      fi
    fi
    echo "key '$KEY_NAME' exists in Garage but its secret is not recoverable" >&2
    echo "either populate $CREDS_FILE with the matching secret, or delete the key:" >&2
    echo "    docker exec $CONTAINER /garage key delete $KEY_NAME" >&2
    exit 1
  fi
  echo "==> creating key: $KEY_NAME"
  create_out="$(garage key create "$KEY_NAME")"
  S3_ACCESS_KEY="$(extract_field "$create_out" "Key ID")"
  S3_SECRET_KEY="$(extract_field "$create_out" "Secret key")"
  if [[ -z "${S3_ACCESS_KEY:-}" || -z "${S3_SECRET_KEY:-}" ]]; then
    echo "failed to parse credentials from 'garage key create' output:" >&2
    printf '%s\n' "$create_out" >&2
    exit 1
  fi
}

allow_key_on_bucket() {
  echo "==> granting $KEY_NAME read+write+owner on $BUCKET"
  garage bucket allow --read --write --owner "$BUCKET" --key "$KEY_NAME" >/dev/null
}

write_creds_file() {
  cat > "$CREDS_FILE" <<EOF
# Generated by e2e/setup-garage.sh -- safe to source into your shell
# or paste into e2e/.env. Local-dev credentials only.
#
# S3_USE_SSL=false matches the http:// endpoint Garage exposes locally;
# the DuckDB httpfs default would otherwise force https and fail
# with "SSL connect error".
S3_ENDPOINT=http://localhost:3900
S3_REGION=garage
S3_ACCESS_KEY=${S3_ACCESS_KEY}
S3_SECRET_KEY=${S3_SECRET_KEY}
S3_BUCKET=${BUCKET}
S3_USE_PATH_STYLE=true
S3_USE_SSL=false
EOF
  echo "==> wrote $CREDS_FILE"
}

# ---- run -------------------------------------------------------------------

wait_for_garage
bootstrap_layout
ensure_key
ensure_bucket
allow_key_on_bucket
write_creds_file

echo
echo "Garage is ready."
echo "  S3 API:  http://localhost:3900   (region: garage, path-style)"
echo "  bucket:  $BUCKET"
echo
echo "Next step: paste the block below into e2e/.env (one-time)."
echo "Examples auto-load e2e/.env, then --storage s3 just works:"
echo "  uv run --project e2e python e2e/01_pipeline_dag/app.py --storage s3"
echo
echo "================================================================"
cat "$CREDS_FILE" | grep -v '^#' | grep -v '^$'
echo "================================================================"
echo
echo "(Same content saved to $CREDS_FILE for re-paste if you lose .env.)"
