"""Python client helpers for the ducklake-cdc DuckDB extension."""

from ducklake_cdc._version import __version__
from ducklake_cdc.client import CDCClient
from ducklake_cdc.enums import (
    ChangeType,
    DdlEventKind,
    DdlObjectKind,
    DiagnosticSeverity,
    EventCategory,
    ScopeKind,
    SubscriptionStatus,
)
from ducklake_cdc.loop import (
    ConsumerBatch,
    ConsumerLoopStats,
    TableChangeBatch,
    iter_consumer_batches,
)
from ducklake_cdc.models import (
    AuditEntry,
    CDCModel,
    ChangeRow,
    ConsumerCommit,
    ConsumerDrop,
    ConsumerForceRelease,
    ConsumerHeartbeat,
    ConsumerListEntry,
    ConsumerReset,
    ConsumerStats,
    ConsumerSubscription,
    ConsumerWait,
    ConsumerWindow,
    DdlEvent,
    DoctorDiagnostic,
    SchemaDiff,
    SnapshotEvent,
    Subscription,
)

__all__ = [
    "AuditEntry",
    "CDCClient",
    "CDCModel",
    "ChangeRow",
    "ChangeType",
    "ConsumerCommit",
    "ConsumerDrop",
    "ConsumerForceRelease",
    "ConsumerHeartbeat",
    "ConsumerBatch",
    "ConsumerListEntry",
    "ConsumerLoopStats",
    "ConsumerReset",
    "ConsumerStats",
    "ConsumerSubscription",
    "ConsumerWait",
    "ConsumerWindow",
    "DdlEvent",
    "DdlEventKind",
    "DdlObjectKind",
    "DiagnosticSeverity",
    "DoctorDiagnostic",
    "EventCategory",
    "SchemaDiff",
    "ScopeKind",
    "SnapshotEvent",
    "Subscription",
    "SubscriptionStatus",
    "TableChangeBatch",
    "__version__",
    "iter_consumer_batches",
]
